server:
    context-path: /log
    port: 8082
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.yc.log.model        